name = "vocab-agent"
compatibility_date = "2026-03-13"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "vocab-db"
database_id = "cb85ce81-1467-49b4-aa90-f35433d09c01"
migrations_dir = "db/migrations"
